---
name: App-ZofCMS-Plugin-GoogleTime
version: 0.0103
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: plugin to get times for different locations using Google
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS::Plugin::Base: 0.0103
  WWW::Google::Time: 0.0103
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::GoogleTime:
    file: lib/App/ZofCMS/Plugin/GoogleTime.pm
    version: 0.0103
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
